NYS-107: Fix bug where wrong bill targeted when multiple bill vote widgets are on same page
nysenate/NYSenate.gov-Website-D9 pull request #169
Opened 2024-04-08 19:57 UTC by nathanielwoodland

Steps to reproduce:
1. Log in as an authenticated user
2. Navigate to: https://www.nysenate.gov/newsroom/press-releases/2024/senate-bolsters-educator-diversity-efforts-new-york-state
3. Click “Aye“ under bill “2023-S1988“
4. Result: Redirected to bill “2023-S3385A“
5. Expected result: Redirected to bill “2023-S1988“

**Technical note for @routinet and @aheaphy:** this fixes a bug in the BillVoteWidgetForm::voteAjaxCallback method by getting the bill ID from the form input (which is always correct) vs. the form build info (which is incorrect in contexts where there are multiple vote widgets present). There may still be an underlying bug on the form build stage, but I avoided larger refactors there as I know we plan to rework this form anyways.

2024-04-11 17:01 UTC, routinet requested changes

2024-04-11 17:01 UTC, routinet commented on web/modules/custom/nys_bill_vote/src/Form/BillVoteWidgetForm.php
> +    if (!empty($user_input['nid'])) {
Use ternary syntax: 
`$bill_path = '/node/' . (empty($user_input['nid']) ? $settings['entity_id'] : $user_input['nid']);`

2024-04-15 15:12 UTC, routinet approved these changes

2024-04-17 18:39 UTC, aheaphy approved these changes

2024-04-22 17:47 UTC, merged